version: '3'
services:
    dynamodb:
        image: amazon/dynamodb-local
        ports:
            - "8000:8000"
        networks:
            - my-network
        volumes:
            - ./collector-dynamodb:/data
        command: "-jar DynamoDBLocal.jar -sharedDb"
networks:
    my-network:
        driver: bridge